chore: add basic golangci-lint configuration.
kulti/thelper pull request #23
Opened 2021-02-06 15:22 UTC by ldez

2021-02-06 21:12 UTC, kulti requested changes
Thank you for your contribution! Previously I've thought that linting lint is strange. Now, I don't.

Some changes are out of my philosophy. I'm glad to merge this PR after changes. Or you can close it and I do similar fixes in my way.

2021-02-06 21:12 UTC, kulti commented on .golangci.yml
> +    check-shadowing: true
I'm ok with shadowing.

Could you please delete this setting and revert the changes of `pkg/analyzer/analyzer.go`?

2021-02-06 21:12 UTC, kulti commented on .golangci.yml
> +run:
It will be great to run the golagci-lint on CI too.

The simplest way is to add the following string to the end of `.github/workflows/ci.yml`:
```yml
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
```

Also, you can refer to [this](https://github.com/Enapter/enapter-cli/blob/master/.github/workflows/ci.yml#L24) as an example.

2021-02-07 02:25 UTC, ldez commented on .golangci.yml
> +run:
My goal was just to add the configuration file, but I can also add the GitHub Action

2021-02-07 06:49 UTC, merged